### ISSUE TITLE
Pass source map to `css-loader`?

### ISSUE THREAD

**Issue by ghost** [fz6m/parcel-css-loader#3]
### Clear and concise description of the problem

Hello and thanks for sharing this plugin with the rest of the community!
I'm having issues passing the generated source map along to `css-loader` while I can get the same thing to work with PostCSS.
With `devtool` of `source-map` and a loader config with PostCSS like:
```js
{
    loader: 'css-loader',
    options: {
        url: false,
        sourceMap: true
    }
},
{
    loader: 'postcss-loader',
    options: {
        postcssOptions: {
            sourceMap: true
        }
    }
},
{
    loader: 'less-loader',
    options: {
        lessOptions: {
            relativeUrls: false,
            sourceMap: true
        }
    }
}
```
I get source maps down to the component file that has the styling:
![sm-postcss](https://user-images.githubusercontent.com/43739279/186359714-98b56af0-4fbc-4394-b732-e6db85253394.PNG)

If I replace the `postcss-loader` with `parcel-css-loader` (autoprefixing works great though), the source maps only point to the parent `.less` file instead of each individual component

```js
{
    loader: 'css-loader',
    options: {
        url: false,
        sourceMap: true
    }
},
{
    loader: 'parcel-css-loader',
    options: {
        sourceMap: true
    }
},
{
    loader: 'less-loader',
    options: {
        lessOptions: {
            relativeUrls: false,
            sourceMap: true
        }
    }
}
```
![sm-parcel](https://user-images.githubusercontent.com/43739279/186359981-2845816d-7418-48cb-a7cc-cb6273bbd9f4.PNG)

Now, I'm not an expert at Webpack, so I may be misusing your loader and you already support this, I checked the source code and I believe I'm passing the `sourceMap` option correctly to your plugin but nothing happens afterward with this source map.
Have you experienced something like this?

### Suggested solution

Have source maps function in a similar way as the `postcss-loader`?

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by fz6m** [comment]
1. check your webpack config [devtool](https://webpack.js.org/configuration/devtool/#devtool) ？

    ```ts
    // webpack.config.js
    
    module.exports = {
      // ...
      devtool: 'cheap-module-source-map'
    }
    ```

2. use specified parcel css instance

    ```bash
      pnpm add @parcel/css
     ```

    ```ts
    // webpack.config.js
    const parcelCSS = require('@parcel/css')
    module.exports = {
      // ...
        loader: 'parcel-css-loader',
        options: {
          implementation: parcelCSS
        }
      // ...
    }
    ```

**Comment by ghost** [comment]
Unfortunately, that did not make a difference. I have created a minimal repo that can reproduce what's described here: 
https://github.com/vgurkov/parcel-css-loader-sourcemaps-issue
If you feel like taking a look. 
Installing dependencies with `npm i` followed by a `npm run build` should build the project.
In the webpack file you can switch between the postcss and parcel loaders by simply uncommenting the one you want to use.
There is a single style in a `component` file and when building the CSS using `postcss-loader`, the source map points to it. If using `parcel-css-loader` it points to the main `style` file.

I would appreciate it if you can take a look. I like using Parcel and I'm so happy that you've made this plugin that we can use.

**Comment by fz6m** [comment]
I did not reproduce.

This is my repo after the webpack build : https://github.com/MoeYc/parcel-css-loader-sourcemaps-issue

![screenshot_2022-08-24_17-55-44](https://user-images.githubusercontent.com/59400654/186389451-dc7767b3-b794-44df-9da4-353624ba3bad.png)

**Comment by ghost** [comment]
Exactly, yes, with `postcss-loader` the source map is more accurate:
![component](https://user-images.githubusercontent.com/43739279/186390853-d4019a30-d785-4fab-aed8-0ab20da63298.PNG)
vs. with `parcel-css-loader`
![parcel](https://user-images.githubusercontent.com/43739279/186390889-3c98f87a-73f2-4fa1-8014-3ed61354fbc8.PNG)

Sorry for not attaching the images earlier.

**Comment by fz6m** [comment]
Thanks for the feedback, supported in version `1.1.0`
