### ISSUE TITLE
Is it possible to use CSS Modules to completely replace 'css-loader'?

### ISSUE THREAD

**Issue by klimashkin** [fz6m/parcel-css-loader#4]
Hi, thank you for creating the loader!

Lightning CSS does support producing CSS Modules, but seems like it doesn't work with `lightningcss-loader`

This works
```js
use: [
  {
    loader: isDev ? 'style-loader' : MiniCssExtractPlugin.loader,
    options: {
      ...(isDev ? {injectType: 'styleTag'} : {esModule: true}),
    },
  },
  {
    loader: 'css-loader',
    options: {
      esModule: isRelease,
      sourceMap: isRelease,
      importLoaders: 1,
      modules: {
        mode: 'local',
        exportGlobals: true,
        exportLocalsConvention: 'asIs',
        localIdentName: '[name]_[local]'
      },
    },
  },
  {
    loader: 'lightningcss-loader',
    options: {
      sourceMap: isRelease,
      analyzeDependencies: false,
      implementation: LightningCSS,
      drafts: {
        nesting: true,
        customMedia: true,
      },
      errorRecovery: false,
      unusedSymbols: [],
    },
  },
],
```

### Suggested solution

But this doesn't work

```js
use: [
  {
    loader: isDev ? 'style-loader' : MiniCssExtractPlugin.loader,
    options: {
      ...(isDev ? {injectType: 'styleTag'} : {esModule: true}),
    },
  },
  {
    loader: 'lightningcss-loader',
    options: {
      sourceMap: isRelease,
      analyzeDependencies: false,
      implementation: LightningCSS,
      cssModules: {
        pattern: '[name]_[local]',
        dashedIdents: false,
      },
      drafts: {
        nesting: true,
        customMedia: true,
      },
      errorRecovery: false,
      unusedSymbols: [],
    },
  },
],
```

### Alternative

It feels a bit excessive to use `css-loader`. Do you think `lightningcss-loader` could replace both `postcss-loader` and `css-loader` in the pipeline?

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by fz6m** [comment]
`lightning-css` is only a css processor and does not integrate with webpack support.

We need the `css-loader` to provide pure css to webpack.

**Comment by onigoetz** [comment]
Hello, I would also be interested by such feature.

`css-loader` uses Postcss internally, and if I use lightningcss I would be happy to not go through postcss after it.

**Comment by Chastrlove** [comment]
https://github.com/vercel/next.js/pull/58712  Next.js has transformed this Repo into a usage similar to css-loader.
@fz6m  老哥能否反向搬运下

**Comment by fz6m** [comment]
css-loader 里要处理的东西是很多的，我不认为 lightning loader 这一个就能代替的了，除非 fork 一整份。

**Comment by slorber** [comment]
Same, I'd like to have this feature

Note that using lightningcss in front of css-loader is probably a bit useless. 

See, css-loader will parse the CSS with postcss anyway, unless postcss-loader is in front, in which case it's able to reuse its pre-parsed AST:

https://github.com/webpack-contrib/css-loader/blob/master/src/index.js#L159

![CleanShot 2024-08-29 at 17 48 57](https://github.com/user-attachments/assets/13412af4-d474-419a-bdec-b4dab168fb3e)


The goal of using lightningcss to me is that we shouldn't need to parse CSS with postcss anymore. We need to get rid of css-loader to truly benefit from lightningcss speed.

**Comment by devongovett** [comment]
@fz6m hey! I'm working with @kdy1 to extract the loader he wrote for Next.js and make it reusable for other webpack users. I'd like to make it more officially maintained as well. Would you be open to donating the npm package name to such an effort? We'd bump a major version when publishing the updated package to ensure nothing existing breaks.

**Comment by fz6m** [comment]
@devongovett Thank you for your interest in this project. 

I have added you and kdy1 as npm package owners. 
if want to move the repo to an organization, contact me anytime ^_^

**Comment by devongovett** [comment]
Thanks for the quick response! I'll work on this soon and give an update here when I make progress.
