### ISSUE TITLE
SyntaxError: Invalid state Error in lightningcss-loader

### ISSUE THREAD

**Issue by jainChetan81** [fz6m/parcel-css-loader#6]
### Describe the bug

I am trying to replace `postcss`, postcss-loader` and `autoprefixer` in my webpack application
this is my current config
```
{
      loader: "css-loader",
      options: {
        importLoaders: isSass ? 2 : 1,
        modules: {
          localIdentName: "[name]__[local]",
          exportOnlyLocals: !isWeb,
        },
      },
    },
    { loader: "postcss-loader" },
```
This is the new config where I replaced postcss with loghtningcss
```
{ loader: "lightningcss-loader", options: { implementation: LightningCSS } },
```
And this is the error I am getting
`SyntaxError: Invalid state Error in lightningcss-loader`
<img width="883" alt="Screenshot 2024-01-18 at 9 47 58 AM" src="https://github.com/fz6m/lightningcss-loader/assets/38555207/6487d162-ed77-49b1-b2ee-826eba18014c">

    

### Reproduction

https://github.com/jainChetan81/lightningcss-error

### System Info

```Shell
System:
    OS: macOS 14.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 37.68 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    pnpm: 8.5.1 - /usr/local/bin/pnpm
    bun: 1.0.22 - ~/.nvm/versions/node/v18.18.2/bin/bun
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.2
```

### Used Package Manager

yarn

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fz6m** [comment]
Check your `src/components/Form/styles.scss` file syntax errors, or give me a minimal reproduction that will work

**Comment by jainChetan81** [comment]
there isn't a syntax error, it works fine with postcss-loader though, I am unable to recreate this without exposing source code
